import type { Metadata } from "next";
import { Cedarville_Cursive, Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const cedarville = Cedarville_Cursive({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
export const playfairDisplay = Playfair_Display({
  variable:"--font-playfair-display",
  subsets:['latin'],
  display: 'swap',
})
 const metadata: Metadata = {
  title: "Affinote - cute templates for your loved ones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${playfairDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
